-- Estrutura da tabela de categorias
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  image_url TEXT,
  ordem INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Estrutura da tabela de produtos
CREATE TABLE IF NOT EXISTS produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  categoria_id BIGINT REFERENCES categorias(id),
  name TEXT NOT NULL,
  secondary_name TEXT,
  subtitle TEXT,
  description TEXT,
  short_description TEXT,
  rating INTEGER DEFAULT 5,
  price DECIMAL(10,2) NOT NULL,
  price_original DECIMAL(10,2),
  price_promotional DECIMAL(10,2),
  images TEXT[] DEFAULT '{}',
  ordem INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT fk_categoria
    FOREIGN KEY(categoria_id) 
    REFERENCES categorias(id)
    ON DELETE SET NULL
);

-- Políticas de segurança para acesso aos dados (RLS)
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;

-- Política para permitir leitura anônima de categorias
CREATE POLICY "Permitir leitura anônima de categorias" 
  ON categorias FOR SELECT 
  USING (true);

-- Política para permitir leitura anônima de produtos
CREATE POLICY "Permitir leitura anônima de produtos" 
  ON produtos FOR SELECT 
  USING (true);

-- Inserir algumas categorias de exemplo
INSERT INTO categorias (name, slug, image_url, ordem) VALUES
  ('Treatment', 'treatment', '/catalogo/Treatment.jpg', 1),
  ('Transformation', 'transformation', '/catalogo/Transformation.jpg', 2),
  ('Home Care', 'home-care', '/catalogo/Home care.jpg', 3),
  ('Finishers', 'finishers', '/catalogo/Finishers.jpg', 4);

-- Inserir alguns produtos de exemplo
INSERT INTO produtos (
  slug, 
  categoria_id, 
  name, 
  secondary_name, 
  subtitle, 
  description, 
  short_description,
  rating,
  price,
  price_original,
  price_promotional,
  images,
  ordem
) VALUES
  (
    'produto-treatment',
    (SELECT id FROM categorias WHERE slug = 'treatment'),
    'Produto Treatment',
    'Tratamento Profissional',
    'Para todos os tipos de cabelo',
    'Tratamento profissional que proporciona resultados imediatos.',
    'Tratamento profissional de alta performance',
    5,
    199.99,
    249.99,
    199.99,
    ARRAY['/catalogo/produtos/1.jpg', '/catalogo/produtos/2.jpg', '/catalogo/produtos/3.jpg'],
    1
  ),
  (
    'produto-transformation',
    (SELECT id FROM categorias WHERE slug = 'transformation'),
    'Produto Transformation',
    'Transformação Total',
    'Transformação completa',
    'Produto para transformação completa dos fios.',
    'Transformação completa para seus cabelos',
    4,
    159.99,
    199.99,
    159.99,
    ARRAY['/catalogo/produtos/4.jpg', '/catalogo/produtos/5.jpg', '/catalogo/produtos/6.jpg'],
    1
  ),
  (
    'produto-home-care',
    (SELECT id FROM categorias WHERE slug = 'home-care'),
    'Produto Home Care',
    'Cuidados Diários',
    'Uso diário',
    'Produto para cuidados diários em casa.',
    'Cuidados diários para seus cabelos',
    5,
    129.99,
    149.99,
    129.99,
    ARRAY['/catalogo/produtos/7.jpg', '/catalogo/produtos/8.jpg', '/catalogo/produtos/9.jpg'],
    1
  ); 