-- NOTA: Este script é apenas para referência.
-- Como os IDs já existem no Supabase, não execute este script.
-- Ele poderia causar conflitos com os dados existentes.

-- Estrutura da tabela de distribuidores
CREATE TABLE IF NOT EXISTS distribuidores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  instagram TEXT,
  address TEXT,
  lat FLOAT,
  lng FLOAT,
  distance TEXT,
  verified BOOLEAN DEFAULT FALSE,
  type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ATENÇÃO: Não insira novos dados se a tabela já existe com dados!
-- Isso é apenas um exemplo de como os dados poderiam ser estruturados

-- Políticas de segurança para acesso aos dados (RLS)
ALTER TABLE distribuidores ENABLE ROW LEVEL SECURITY;

-- Política para permitir leitura anônima
CREATE POLICY "Permitir leitura anônima de distribuidores" 
  ON distribuidores FOR SELECT 
  USING (true); 